const mongoose = require('mongoose');

// Define a schema for the items within an order
const OrderItemSchema = new mongoose.Schema({
  id: { type: String, required: true },
  name: { type: String, required: true },
  price: { type: Number, required: true },
  quantity: { type: Number, required: true },
  imageUrl: { type: String, required: false },
});

// Define the main order schema
const OrderSchema = new mongoose.Schema({
  // The unique ID generated by the frontend for confirmation display
  orderId: {
    type: String,
    required: true,
    unique: true,
  },
  // An array of items, based on the schema defined above
  items: [OrderItemSchema],
  // The total cost of the order
  total: {
    type: Number,
    required: true,
  },
  // Customer's shipping information
  shippingDetails: {
    name: { type: String, required: true },
    address: { type: String, required: true },
    city: { type: String, required: true },
    postalCode: { type: String, required: true },
  },
  // The date the order was placed, defaults to the current time
  orderDate: {
    type: Date,
    default: Date.now,
  },
});

// Create and export the Order model based on the schema
module.exports = mongoose.model('Order', OrderSchema);
